import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import UnicornBackground from '@/app/components/UnicornBackground'
import WatermarkRemover from '@/app/components/WatermarkRemover'
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", 
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen w-full`}>
        {/* Компонент для удаления водяного знака */}
        <WatermarkRemover />
        
        {/* Фоновая анимация */}
        <UnicornBackground projectId="bvspPQLSZj0ipL9pUQmJ" />
        
        {/* Основной контент */}
        <main className="relative z-10 w-full min-w-full">
          {children}
        </main>
      </body>
    </html>
  )
}